config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/home/", to: "home#show"
  root "home#show"

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :posts, only: [:index, :show]
  get 'posts/:id/share/:social_media', to: 'posts#share', as: :share_post


  namespace :admin do
    resources :posts, except: %i[new destroy edit]
    resources :analytics, only: :index
    get 'cms/write', to: 'posts#new', as: :new_post
    put 'posts/:id/publish', to: 'posts#publish', as: :publish_post
    get 'posts/:id/edit', to: 'posts#edit', as: :edit_post
    put 'posts/:id/unpublish', to: 'posts#unpublish', as: :unpublish_post
    delete 'posts/:id', to: 'posts#destroy', as: :destroy_post

    get '/login', to: 'sessions#new'
    post '/sessions', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

  end

  get "/about/", to: "about#show"

  get '/sitemap.xml.gz', to: redirect("https://#{Rails.application.credentials.dig(:aws, :prod, :sitemap_bucket)}.s3.#{Rails.application.credentials.dig(:aws, :region)}.amazonaws.com/sitemap.xml.gz")

  get '/feed.xml', to: "posts#rss_feed", as: :rss_feed, constraints: { format: 'rss' }

  namespace :api do
    post 'subscriptions/register', to: 'subscriptions#register', as: :new_subscription
  end
end

app/views/shared/_admin_edit_buttons.html.erb
<% if @post.draft? %>

  <%= button_to "Publish", admin_publish_post_path(id: @post.id), method: :put,
    class: "float-right bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mx-2"  %>
<% elsif @post.published? %>
  <%= button_to "Unpublish", admin_unpublish_post_path(id: @post.id), method: :put,
    class: "float-right bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mx-2"  %>
<% end %>
<%= button_to "Delete", admin_destroy_post_path(id: @post.id), method: :delete, class: "float-right bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded mx-2"  %>
<%= button_to "Edit", admin_edit_post_path(id: @post.id), method: :get,
  class: "float-right bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded mx-2"  %>

app/views/shared/_footer.html.erb
<footer class="px-10 font-semibold lg:px-5 bg-gradient-to-r from-red-500 to-indigo-700 dark:from-indigo-700 dark:to-blue-900">
  <div class="py-16 text-5xl text-white lg:m-auto lg:w-3/4 lg:text-xl">
    <ul class="tracking-tight text-center">
      <li class="inline">
        <a href="https://twitter.com/anakbns" target="_blank" class="pr-20 md:pr-15">Twitter</a>
      </li>
      <li class="inline">
        <a href="https://github.com/anansilva" target="_blank" class="pr-20 md:pr-15">GitHub</a>
      </li>
      <li class="inline">
        <a href="https://linkedin.com/in/anans" target="_blank" class="pr-20 md:pr-15">LinkedIn</a>
      </li>
      <li class="inline">
        <a href="<%= rss_feed_url(format: 'rss') %>" target="_blank">RSS</a>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_meta_tags.html.erb
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">
<meta name="keywords" content="<%= meta_keywords %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">

<!-- Linked Card data -->
<meta prefix="og: http://ogp.me/ns#" property="og:type" content="website" />
<meta prefix="og: http://ogp.me/ns#" property="og:title" content="<% meta_title %>" />
<meta prefix="og: http://ogp.me/ns#" property="og:description" content="<% meta_description %>" />
<meta prefix="og: http://ogp.me/ns#" property="og:image" content="<% meta_image %>" />
<meta prefix="og: http://ogp.me/ns#" property="og:url" content="<% request.original_url %>" />

app/views/shared/_navbar.html.erb
<header class="flex items-center px-10 pb-5 lg:px-5">
  <div class="flex-grow pt-10 text-6xl font-extrabold tracking-tighter text-transparent lg:pt-5 lg:text-2xl bg-clip-text bg-gradient-to-r from-red-500 to-indigo-700 dark:from-indigo-500 dark:to-blue-800">
    <a href="/">Ana Nunes da Silva</a>
  </div>

  <div class="pt-10 text-4xl font-semibold sm:hidden lg:block lg:pt-5 lg:flex-grow lg:text-right text-md lg:text-xl">
    <ul class="tracking-tight">
      <li class="inline">
        <%= link_to 'About', about_path, method: :get, class: "py-4 pr-4 px-6 hover:underline" %>
      </li>
      <li class="inline">
        <%= link_to 'Posts', posts_path, method: :get, class: "py-4 pr-4 px-6 hover:underline" %>
      </li>
      <% if current_user %>
        <li class="inline">
          <%= link_to 'Preview', admin_posts_path, method: :get, class: "py-3 pr-4 px-6 hover:underline" %>
        </li>
        <li class="inline">
          <%= link_to 'New Post', admin_new_post_path, method: :get, class: "py-4 pr-4 px-6 hover:underline" %>
        </li>
        <li class="inline">
          <%= link_to 'Dashboard', admin_analytics_path, method: :get, class: "py-4 pr-4 px-6 hover:underline" %>
        </li>
        <li class="inline">
          <%= link_to 'Logout', admin_logout_path, method: :delete, class: "py-4 pr-4 px-6 hover:underline" %>
        </li>
      <% end %>
    </ul>
  </div>

  <%# data-controller with the name of the controller that will listen to the events on this element %>
  <div class="relative inline-block pt-10 text-center lg:hidden" data-controller="menu">
  <%# data-action with the event type that will trigger a toggle function on the menu controller %>
    <button data-action="click->menu#toggle" type="button" class="inline-flex justify-center w-full px-4 py-2 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-indigo-500"
      id="options-menu" aria-haspopup="true" aria-expanded="true">
      <svg viewBox="0 0 100 80" width="60" height="60">
          <rect width="100" height="20" rx="8"></rect>
          <rect y="30" width="100" height="20" rx="8"></rect>
          <rect y="60" width="100" height="20" rx="8"></rect>
      </svg>
    </button>

  <%# data-target what the target of our function will be %>
  <div class="absolute right-0 hidden mt-2 bg-white shadow-lg w-96 origin-top-right rounded-md ring-1 ring-black ring-opacity-5"
    data-menu-target="toggleable">
      <div class="py-6" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
        <a href="/about" class="block px-4 py-6 text-5xl text-gray-700 hover:bg-gray-100 hover:text-gray-900" role="menuitem">About</a>
        <a href="/posts" class="block px-4 py-6 text-5xl text-gray-700 hover:bg-gray-100 hover:text-gray-900" role="menuitem">Posts</a>
      </div>
    </div>
  </div>

</header>

app/views/shared/_newsletter_subscription.html.erb
<div data-controller="subscription" class="pt-8 mt-20 text-center bg-gray-100 border border-gray-100 rounded shadow-md dark:border-gray-800 dark:bg-gray-800 dark:border-gray-300" %>
  <h2 class="text-5xl tracking-wide lg:text-4xl">Subscribe below to get future blog posts</h2>
  <%= form_with url: api_new_subscription_url,
    data: { action: "ajax:success->subscription#onSuccess ajax:error->subscription#onError" },
    method: :post do |form| %>
    <div data-subscription-target="email">
      <%= form.email_field :email, placeholder: "Enter your email",
        class: "w-1/3 py-1 px-2 m-2 border rounded focus:outline-none focus:border-indigo-500 text-gray-900 dark:text-gray-300 dark:bg-gray-900" %>
      <%= form.submit 'subscribe', id: "newsletter-btn",
        class: "cursor-pointer py-1 px-2 rounded focus:outline-none text-gray-200 border-gray-300 bg-indigo-700" %>
    </div>
  <% end %>

  <p class="pt-6 text-sm text-gray-600 dark:text-gray-300">No spam, no ads. Unsubscribe any time.</p>
</div>

app/views/shared/_pagination.html.erb
<div class="flex items-center justify-center my-10 text-4xl font-semibold tracking-wide text-indigo-700 lg:text-xl dark:text-indigo-500" %>
  <% if  pagination.previous_page? %>
    <%= link_to 'First', posts_path(page: 1) %>
    <%= link_to '< Previous', posts_path(page: pagination.previous_page), class: "lg:ml-6 ml-12" %>
  <% else %>
    <p class="text-gray-300 dark:text-gray-700">First</p>
    <p class="text-gray-300 lg:ml-6 dark:text-gray-700">&#60; Previous</p>
  <% end %>
  <p class="ml-12 font-normal text-gray-900 lg:ml-6 lg:text-base dark:text-gray-300"><%= "Page #{pagination.page} of #{pagination.total_pages}" %></p>
  <% if pagination.next_page? %>
    <%= link_to 'Next >', posts_path(page: pagination.next_page), class: "lg:ml-6 ml-12" %>
    <%= link_to 'Last', posts_path(page: pagination.total_pages), class: "lg:ml-6 ml-12" %>
  <% else %>
    <p class="ml-12 text-gray-300 lg:ml-6 dark:text-gray-700">Next &#62;</p>
    <p class="ml-12 text-gray-300 lg:ml-6 dark:text-gray-700">Last </p>
  <% end %>
</div>

app/views/shared/_post_analytics.html.erb
<p class="text-sm text-gray-600">
  Total views: <%=  @post_views[:total_views] %>
</p>
<p class="text-sm text-gray-600">
  Unique views: <%=  @post_views[:unique_total_views] %>
</p>

app/views/shared/_post_card.html.erb
<div class="w-full pb-12 mb-6 lg:pr-4 lg:w-1/3 xl:w-1/3">
  <article class="overflow-hidden">
    <% if post.cover_image.attached? %>
      <%= image_tag post.cover_image.variant(resize_to_limit: [300, 300]), alt: "#{post.title} cover image", class: 'h-full w-full cursor-pointer' %>
    <% end %>
    <div class="container px-4 pt-8 mx-auto leading-relaxed lg:mx-0 lg:pt-4 lg:leading-normal">
      <h1 class="mb-2 text-5xl font-extrabold tracking-wide lg:mb-1 lg:text-2xl hover:underline">
        <%= link_to post.title, post %>&nbsp;<%= '[DRAFT]' if post.draft? %>
      </h1>
      <p class="mb-4 text-3xl text-gray-600 lg:mb-2 lg:text-sm">
        <%= post.published_at&.strftime('%b, %Y') %>
      <p>
      <p class="overflow-hidden text-4xl text-gray-800 dark:text-gray-50 overflow-ellipsis lg:text-base">
        <%= post.intro %><br>
        <%= link_to 'Keep reading >>', link_to_post(post), class: "hover:underline sm:text-3xl lg:text-sm font-bold uppercase text-indigo-700 dark:text-indigo-500"%>
      </p>
    </div>
  </article>
</div>

app/views/shared/_tags.html.erb
<div class="container sticky z-10 top-0 bg-white flex flex-wrap pb-8 pt-8 justify-center w-full mx-auto font-normal sm:text-3xl lg:text-lg text-gray-500 tracking-wide">
  <%= link_to all_posts, class: "block sm:px-6 lg:px-4 uppercase #{all_tag}" do %>
    <%= 'All' =%>
  <% end %>
  <% Tag.all.each do |tag| %>
    <%= link_to filter_posts(tag.name), class: "block sm:px-6 lg:px-4 uppercase #{active_tag(tag.name)} #{hover_tag(tag.name)}" do %>
      <%= tag.name =%>
    <% end %>
  <% end %>
</div>